# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  EnvironmentName: 'dev'
  Resource: '"Controls and Assurance Tool API Dev"'
  Scope: 'user_impersonation'
  IncludeWebAPIPermissionRequest: True



steps:
- task: NodeTool@0
  displayName: 'Use Node 8.9.4'
  inputs:
    versionSpec: '>=8.9.4 < 9.0.0'

#- script: |
#    npm install
#    npm run build
#  displayName: 'npm install and build'

- task: Npm@1
  displayName: 'npm install'
  inputs:
    command: 'install'
    workingDir: 'control-assurance-sp'
    verbose: false

- task: Gulp@0
  displayName: 'Run gulp set-web-api-permission-request'
  inputs:
    gulpFile: 'control-assurance-sp/gulpfile.js'
    targets: 'set-web-api-permission-request'
    arguments: '--resource $(Resource) --scope $(Scope)'
  condition: and(succeeded(), eq(variables['IncludeWebAPIPermissionRequest'], 'True'))

- task: Gulp@0
  displayName: 'Run gulp bundle'
  inputs:
    gulpFile: 'control-assurance-sp/gulpfile.js'
    targets: bundle
    arguments: '--ship'
    workingDirectory: 'control-assurance-sp'

- task: Gulp@0
  displayName: 'Run gulp package-solution'
  inputs:
    gulpFile: 'control-assurance-sp/gulpfile.js'
    targets: 'package-solution'
    arguments: '--ship'
    workingDirectory: 'control-assurance-sp'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: 'control-assurance-sp/sharepoint/solution/'
    Contents: 'caat-webparts.sppkg'
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts: drop'

