#!/bin/bash

######################################################################################################
# Script: delete-sql-database
#
# This script deletes the SQL database for the given environment
#
# Parameters: None but see note
#
# Note: env, appShortname and appDisplayName should be set as environment vars
# Req by set-resource-names 
#
######################################################################################################

# Set-up common resource names (execute in current shell)
. set-resource-names 

echo "Started - Delete SQL Database - $sqlDatabaseName "

if az sql db show --name $sqlDatabaseName --server $sqlInstanceName --resource-group $resourceGroupName
then
    echo "Backing-up SQL database $sqlDatabaseName..."

    backupDatabaseName="$sqlInstanceName-$(date +"%Y-%m-%d-%H-%M")"
    az sql db copy --server $sqlInstanceName --name $sqlDatabaseName --resource-group $resourceGroupName --dest-name $backupDatabaseName --service-objective S0

    echo "Deleting SQL database $sqlDatabaseName..."

    az sql db delete --server $sqlInstanceName --name $sqlDatabaseName --resource-group $resourceGroupName --yes
else
    echo "SQL Azure Database does not exist - no action required"
fi

echo "Completed - Delete SQL Database - $sqlDatabaseName "
