#!/bin/bash

######################################################################################################
# Script: install-appreg
#
# This script provisions and configures the following resources in Azure to support deployment 
# of a BEIS Digital application:
#
#     * App Registration
#
# Parameters: None but see note
#
# Note: env, appShortname, appDisplayName and adDomain should be set as environment vars
# First 3 are req by set-resource-names and adDomain is like beisdigitaldev.onmicrosoft.com
#
######################################################################################################

set -e

. set-resource-names 

appRegistrationIdentifierUri=https://$adDomain/${appShortname}API${env^}

echo "Started - Install App Registration - $appRegistrationDisplayName "

if az ad app show --id $appRegistrationIdentifierUri
then
    echo "App Registration already exists - no action required"
else
    # Create an App Registration
    az ad app create --display-name "$appRegistrationDisplayName" --available-to-other-tenants false --homepage $webApiRootUrl --oauth2-allow-implicit-flow false --reply-urls $webApiRootUrl/.auth/login/aad/callback --identifier-uris $appRegistrationIdentifierUri --required-resource-accesses @corporate-reporting-appreg-required-resource-accesses.json
fi

echo "Creating Service Principal $appRegistrationDisplayName..."

if az ad sp show --id $appRegistrationIdentifierUri
then
    echo "Service Principal already exists - no action required"
else
    # Create a Service Principal (this appears in the Enterprise Applications list in the Azure Portal)
    az ad sp create --id $appRegistrationIdentifierUri
    az ad sp update --id $appRegistrationIdentifierUri --add tags WindowsAzureActiveDirectoryIntegratedApp
fi

echo "Completed - Install App Registration - $appRegistrationDisplayName "
