#!/bin/bash

######################################################################################################
# Script: reset-sql-admin-password
#
# This script changes the SQL Admin password for the Corporate Reporting SQL database for the given environment
#
# The script requires the following environment variables to be set:
#
#     env - The environment name
#      - The new admin password
Parameters: None but see note
#
# Note: env, appShortname, appDisplayName and adminPassword should be set as environment vars
# First 3 are req by set-resource-names and adminPassword is the new admin password
#
######################################################################################################


# Set-up common resource names (execute in current shell)
. set-resource-names

echo "Started - SQL Database Admin Password - $appDisplayName "

if az sql server show --name $sqlInstanceName --resource-group $resourceGroupName
then
    echo "Changing SQL Admin password..."

    az sql server update --name $sqlInstanceName --resource-group $resourceGroupName --admin-password $adminPassword
else
    echo "SQL Azure Database Server does not exist - no action required"
fi

echo "Completed - SQL Database Admin Password - $appDisplayName "
