#!/bin/bash

######################################################################################################
# Script: set-resource-names
#
# This script defines the names of the Azure resources that will be created by the provisionsing process.
# It is called by the provisioning scripts so that a common set of resource names is used.
#
# Note: Containers and storage cannot have '-' in the name.
#
# Requires Environment Variables:
#
#   1) env - The environment name
#   2) appShortname - shortname for application, should not have '-' in the name
#   3) appDisplayName - a full long name 
#
######################################################################################################

# exit if required environment vars have not been defined

if [ -z "$env" ]; then
    echo \$env is not defined as an environment Variables
    exit 1
fi

if [ -z "$appShortname" ]; then
    echo \$appShortname is not defined as an environment Variables
    exit 1
fi

if [ -z "$appDisplayName" ]; then
    echo \$appDisplayName is not defined as an environment Variables
    exit 1
fi


export resourceGroupName = $env-$appShortname
export storageAccountName = ${env}${appShortname}
export containerName = ${env}${appShortname}api
export sqlBackupContainerName = ${env}${appShortname}api
export appServicePlanName = AppServicePlan${env^}
export webAppName = $env-$appShortname-api
export functionAppServicePlanName = FunctionAppServicePlan${env^}
export functionAppName = $env-$appShortname-reminders
export functionAppSettingsFileName = reminders.appSettings
export sqlInstanceName = $env-$appShortname-sql
export sqlDatabaseName = $env-$appShortname-db
export apiSecurityGroupName = "APP - U - $appDisplayName - API Users"
export adminSecurityGroupName = "APP - U - $appDisplayName - Admin Users"
export reportingSecurityGroupName = "APP - U - $appDisplayName - Reports Users"
export supportSecurityGroupName = "APP - U - $appDisplayName - Support Users"
export dataCentre = uksouth
export sqlFirewallRuleName = "${appDisplayName} (${env^}) access from Azure Services"
export zscalarFirewallRuleName = "Zscaler London III"
export appRegistrationDisplayName = "${appDisplayName} API ${env^}"
export webApiRootUrl = https://$webAppName.azurewebsites.net