CREATE TABLE [dbo].[DefElement] (
    [ID]                           INT             IDENTITY (1, 1) NOT NULL,
    [DefElementGroupId]            INT             NULL,
    [Title]                        NVARCHAR (100)  NULL,
    [ElementObjective]             NVARCHAR (MAX)  NULL,
    [SectionATitle]                NVARCHAR (500)  NULL,
    [SectionAHelp]                 NVARCHAR (MAX)  NULL,
    [SectionANumQuestions]         INT             NULL,
    [SectionAQuestion1]            NVARCHAR (1000) NULL,
    [SectionAQuestion2]            NVARCHAR (1000) NULL,
    [SectionAQuestion3]            NVARCHAR (1000) NULL,
    [SectionAQuestion4]            NVARCHAR (1000) NULL,
    [SectionAQuestion5]            NVARCHAR (1000) NULL,
    [SectionAQuestion6]            NVARCHAR (1000) NULL,
    [SectionAQuestion7]            NVARCHAR (1000) NULL,
    [SectionAQuestion8]            NVARCHAR (1000) NULL,
    [SectionAQuestion9]            NVARCHAR (1000) NULL,
    [SectionAQuestion10]           NVARCHAR (1000) NULL,
    [SectionAOtherQuestion]        NVARCHAR (1000) NULL,
    [SectionAOtherBoxText]         NVARCHAR (500)  NULL,
    [SectionAEffectQuestion]       NVARCHAR (1000) NULL,
    [SectionAEffectNote]           NVARCHAR (500)  NULL,
    [SectionAEffectBoxText]        NVARCHAR (500)  NULL,
    [SectionBTitle]                NVARCHAR (500)  NULL,
    [SectionBHelp]                 NVARCHAR (MAX)  NULL,
    [SectionBNumQuestions]         INT             NULL,
    [SectionBQuestion1]            NVARCHAR (1000) NULL,
    [SectionBBoxText1]             NVARCHAR (500)  NULL,
    [SectionBEffect1]              NVARCHAR (1000) NULL,
    [SectionBNote1]                NVARCHAR (500)  NULL,
    [SectionBQuestion2]            NVARCHAR (1000) NULL,
    [SectionBBoxText2]             NVARCHAR (500)  NULL,
    [SectionBEffect2]              NVARCHAR (1000) NULL,
    [SectionBNote2]                NVARCHAR (500)  NULL,
    [SectionBQuestion3]            NVARCHAR (1000) NULL,
    [SectionBBoxText3]             NVARCHAR (500)  NULL,
    [SectionBEffect3]              NVARCHAR (1000) NULL,
    [SectionBNote3]                NVARCHAR (500)  NULL,
    [SectionBQuestion4]            NVARCHAR (1000) NULL,
    [SectionBBoxText4]             NVARCHAR (500)  NULL,
    [SectionBEffect4]              NVARCHAR (1000) NULL,
    [SectionBNote4]                NVARCHAR (500)  NULL,
    [SectionATitleHelpId]          INT             NULL,
    [SectionAQuestion1HelpId]      INT             NULL,
    [SectionAQuestion2HelpId]      INT             NULL,
    [SectionAQuestion3HelpId]      INT             NULL,
    [SectionAQuestion4HelpId]      INT             NULL,
    [SectionAQuestion5HelpId]      INT             NULL,
    [SectionAQuestion6HelpId]      INT             NULL,
    [SectionAQuestion7HelpId]      INT             NULL,
    [SectionAQuestion8HelpId]      INT             NULL,
    [SectionAQuestion9HelpId]      INT             NULL,
    [SectionAQuestion10HelpId]     INT             NULL,
    [SectionAOtherQuestionHelpId]  INT             NULL,
    [SectionAEffectQuestionHelpId] INT             NULL,
    [SectionBTitleHelpId]          INT             NULL,
    [SectionBQuestion1HelpId]      INT             NULL,
    [SectionBQuestion2HelpId]      INT             NULL,
    [SectionBQuestion3HelpId]      INT             NULL,
    [SectionBQuestion4HelpId]      INT             NULL,
    [PeriodId]                     INT             NULL,
    CONSTRAINT [PK_DefElement] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_DefElement_DefElementGroup] FOREIGN KEY ([DefElementGroupId]) REFERENCES [dbo].[DefElementGroup] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [FK_DefElement_Period] FOREIGN KEY ([PeriodId]) REFERENCES [dbo].[Period] ([ID])
);

