CREATE TABLE [dbo].[Element] (
    [ID]                             INT            IDENTITY (1, 1) NOT NULL,
    [FormId]                         INT            NOT NULL,
    [DefElementId]                   INT            NULL,
    [Title]                          NVARCHAR (100) NULL,
    [Status]                         NVARCHAR (50)  NULL,
    [CompletedOn]                    DATETIME       NULL,
    [AssignedTo]                     INT            NULL,
    [GeneralNote]                    NVARCHAR (MAX) NULL,
    [ResponseA1]                     NVARCHAR (50)  NULL,
    [ResponseA2]                     NVARCHAR (50)  NULL,
    [ResponseA3]                     NVARCHAR (50)  NULL,
    [ResponseA4]                     NVARCHAR (50)  NULL,
    [ResponseA5]                     NVARCHAR (50)  NULL,
    [ResponseA6]                     NVARCHAR (50)  NULL,
    [ResponseA7]                     NVARCHAR (50)  NULL,
    [ResponseA8]                     NVARCHAR (50)  NULL,
    [ResponseA9]                     NVARCHAR (50)  NULL,
    [ResponseA10]                    NVARCHAR (50)  NULL,
    [ResponseAOther]                 NVARCHAR (50)  NULL,
    [ResponseAOtherText]             NVARCHAR (MAX) NULL,
    [ResponseAEffect]                NVARCHAR (50)  NULL,
    [ResponseAEffectText]            NVARCHAR (MAX) NULL,
    [ResponseB1]                     NVARCHAR (50)  NULL,
    [ResponseB1Text]                 NVARCHAR (MAX) NULL,
    [ResponseB1Effect]               NVARCHAR (50)  NULL,
    [ResponseB2]                     NVARCHAR (50)  NULL,
    [ResponseB2Text]                 NVARCHAR (MAX) NULL,
    [ResponseB2Effect]               NVARCHAR (50)  NULL,
    [ResponseB3]                     NVARCHAR (50)  NULL,
    [ResponseB3Text]                 NVARCHAR (MAX) NULL,
    [ResponseB3Effect]               NVARCHAR (50)  NULL,
    [ResponseB4]                     NVARCHAR (50)  NULL,
    [ResponseB4Text]                 NVARCHAR (MAX) NULL,
    [ResponseB4Effect]               NVARCHAR (50)  NULL,
    [NotApplicable]                  BIT            NULL,
    [ResponseAEffectUnsatisfactory]  BIT            NULL,
    [ResponseAEffectLimited]         BIT            NULL,
    [ResponseAEffectModerate]        BIT            NULL,
    [ResponseAEffectSubstantial]     BIT            NULL,
    [ResponseAEffectNotApplicable]   BIT            NULL,
    [ResponseB1EffectUnsatisfactory] BIT            NULL,
    [ResponseB1EffectLimited]        BIT            NULL,
    [ResponseB1EffectModerate]       BIT            NULL,
    [ResponseB1EffectSubstantial]    BIT            NULL,
    [ResponseB1EffectNotApplicable]  BIT            NULL,
    [ResponseB2EffectUnsatisfactory] BIT            NULL,
    [ResponseB2EffectLimited]        BIT            NULL,
    [ResponseB2EffectModerate]       BIT            NULL,
    [ResponseB2EffectSubstantial]    BIT            NULL,
    [ResponseB2EffectNotApplicable]  BIT            NULL,
    [ResponseB3EffectUnsatisfactory] BIT            NULL,
    [ResponseB3EffectLimited]        BIT            NULL,
    [ResponseB3EffectModerate]       BIT            NULL,
    [ResponseB3EffectSubstantial]    BIT            NULL,
    [ResponseB3EffectNotApplicable]  BIT            NULL,
    CONSTRAINT [PK_Element] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_Element_DefElement] FOREIGN KEY ([DefElementId]) REFERENCES [dbo].[DefElement] ([ID]),
    CONSTRAINT [FK_Element_Form] FOREIGN KEY ([FormId]) REFERENCES [dbo].[Form] ([ID])
);

