//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlAssuranceAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditFeedback
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Details { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> TeamId { get; set; }
        public Nullable<int> PeriodId { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
    
        public virtual Period Period { get; set; }
        public virtual Team Team { get; set; }
        public virtual User User { get; set; }
    }
}
