//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlAssuranceAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DefForm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DefForm()
        {
            this.DefElementGroups = new HashSet<DefElementGroup>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public string Status { get; set; }
        public string Details { get; set; }
        public string SignOffSectionTitle { get; set; }
        public string DDSignOffTitle { get; set; }
        public string DDSignOffText { get; set; }
        public string DirSignOffTitle { get; set; }
        public string DirSignOffText { get; set; }
        public Nullable<int> PeriodId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DefElementGroup> DefElementGroups { get; set; }
        public virtual Period Period { get; set; }
    }
}
