//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlAssuranceAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Form()
        {
            this.Elements = new HashSet<Element>();
        }
    
        public int ID { get; set; }
        public Nullable<int> PeriodId { get; set; }
        public Nullable<int> TeamId { get; set; }
        public Nullable<int> DefFormId { get; set; }
        public string Title { get; set; }
        public Nullable<bool> DDSignOffStatus { get; set; }
        public Nullable<int> DDSignOffUserId { get; set; }
        public Nullable<System.DateTime> DDSignOffDate { get; set; }
        public Nullable<bool> DirSignOffStatus { get; set; }
        public Nullable<int> DirSignOffUserId { get; set; }
        public Nullable<System.DateTime> DirSignOffDate { get; set; }
        public string LastSignOffFor { get; set; }
        public Nullable<bool> FirstSignedOff { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Element> Elements { get; set; }
        public virtual Period Period { get; set; }
        public virtual Team Team { get; set; }
    }
}
