//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlAssuranceAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IAPActionDirectorate
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public Nullable<int> IAPActionId { get; set; }
        public Nullable<int> DirectorateId { get; set; }
    
        public virtual Directorate Directorate { get; set; }
        public virtual IAPAction IAPAction { get; set; }
    }
}
