//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlAssuranceAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLDefForm
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Details { get; set; }
        public string EngagedStageFormText { get; set; }
        public string OnboardingStageFormText { get; set; }
        public string LeavingStageFormText { get; set; }
        public string CaseDetailsHelpText { get; set; }
        public string DetailsOfApplicantEditHelpText { get; set; }
        public string DetailsOfApplicantViewHelpText { get; set; }
        public string RequirementEditHelpText { get; set; }
        public string RequirementViewHelpText { get; set; }
        public string CommercialEditHelpText { get; set; }
        public string CommercialViewHelpText { get; set; }
        public string ResourcingJustificationEditHelpText { get; set; }
        public string ResourcingJustificationViewHelpText { get; set; }
        public string FinanceEditHelpText { get; set; }
        public string FinanceViewHelpText { get; set; }
        public string OtherEditHelpText { get; set; }
        public string OtherViewHelpText { get; set; }
        public string ApproversEditHelpText { get; set; }
        public string ApproversViewHelpText { get; set; }
        public string BHApprovalDecisionEditHelpText { get; set; }
        public string BHApprovalDecisionViewHelpText { get; set; }
        public string FBPApprovalDecisionEditHelpText { get; set; }
        public string FBPApprovalDecisionViewHelpText { get; set; }
        public string HRBPApprovalDecisionEditHelpText { get; set; }
        public string HRBPApprovalDecisionViewHelpText { get; set; }
        public string ICApprovalDecisionEditHelpText { get; set; }
        public string ICApprovalDecisionViewHelpText { get; set; }
        public string OnboardingEditHelpText { get; set; }
        public string OnboardingViewHelpText { get; set; }
        public string EngagedEditHelpText { get; set; }
        public string EngagedViewHelpText { get; set; }
        public string LeavingEditHelpText { get; set; }
        public string LeavingViewHelpText { get; set; }
        public string CaseDiscussionHelpText { get; set; }
        public string CBPApprovalDecisionEditHelpText { get; set; }
        public string CBPApprovalDecisionViewHelpText { get; set; }
    }
}
