//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlAssuranceAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DefElementGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DefElementGroup()
        {
            this.DefElements = new HashSet<DefElement>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<int> DefFormId { get; set; }
        public Nullable<int> PeriodId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DefElement> DefElements { get; set; }
        public virtual DefForm DefForm { get; set; }
        public virtual Period Period { get; set; }
    }
}
