//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlAssuranceAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DefElement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DefElement()
        {
            this.Elements = new HashSet<Element>();
        }
    
        public int ID { get; set; }
        public Nullable<int> DefElementGroupId { get; set; }
        public string Title { get; set; }
        public string ElementObjective { get; set; }
        public string SectionATitle { get; set; }
        public string SectionAHelp { get; set; }
        public Nullable<int> SectionANumQuestions { get; set; }
        public string SectionAQuestion1 { get; set; }
        public string SectionAQuestion2 { get; set; }
        public string SectionAQuestion3 { get; set; }
        public string SectionAQuestion4 { get; set; }
        public string SectionAQuestion5 { get; set; }
        public string SectionAQuestion6 { get; set; }
        public string SectionAQuestion7 { get; set; }
        public string SectionAQuestion8 { get; set; }
        public string SectionAQuestion9 { get; set; }
        public string SectionAQuestion10 { get; set; }
        public string SectionAOtherQuestion { get; set; }
        public string SectionAOtherBoxText { get; set; }
        public string SectionAEffectQuestion { get; set; }
        public string SectionAEffectNote { get; set; }
        public string SectionAEffectBoxText { get; set; }
        public string SectionBTitle { get; set; }
        public string SectionBHelp { get; set; }
        public Nullable<int> SectionBNumQuestions { get; set; }
        public string SectionBQuestion1 { get; set; }
        public string SectionBBoxText1 { get; set; }
        public string SectionBEffect1 { get; set; }
        public string SectionBNote1 { get; set; }
        public string SectionBQuestion2 { get; set; }
        public string SectionBBoxText2 { get; set; }
        public string SectionBEffect2 { get; set; }
        public string SectionBNote2 { get; set; }
        public string SectionBQuestion3 { get; set; }
        public string SectionBBoxText3 { get; set; }
        public string SectionBEffect3 { get; set; }
        public string SectionBNote3 { get; set; }
        public string SectionBQuestion4 { get; set; }
        public string SectionBBoxText4 { get; set; }
        public string SectionBEffect4 { get; set; }
        public string SectionBNote4 { get; set; }
        public Nullable<int> SectionATitleHelpId { get; set; }
        public Nullable<int> SectionAQuestion1HelpId { get; set; }
        public Nullable<int> SectionAQuestion2HelpId { get; set; }
        public Nullable<int> SectionAQuestion3HelpId { get; set; }
        public Nullable<int> SectionAQuestion4HelpId { get; set; }
        public Nullable<int> SectionAQuestion5HelpId { get; set; }
        public Nullable<int> SectionAQuestion6HelpId { get; set; }
        public Nullable<int> SectionAQuestion7HelpId { get; set; }
        public Nullable<int> SectionAQuestion8HelpId { get; set; }
        public Nullable<int> SectionAQuestion9HelpId { get; set; }
        public Nullable<int> SectionAQuestion10HelpId { get; set; }
        public Nullable<int> SectionAOtherQuestionHelpId { get; set; }
        public Nullable<int> SectionAEffectQuestionHelpId { get; set; }
        public Nullable<int> SectionBTitleHelpId { get; set; }
        public Nullable<int> SectionBQuestion1HelpId { get; set; }
        public Nullable<int> SectionBQuestion2HelpId { get; set; }
        public Nullable<int> SectionBQuestion3HelpId { get; set; }
        public Nullable<int> SectionBQuestion4HelpId { get; set; }
        public Nullable<int> PeriodId { get; set; }
    
        public virtual DefElementGroup DefElementGroup { get; set; }
        public virtual Period Period { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Element> Elements { get; set; }
    }
}
