//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlAssuranceAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Directorate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Directorate()
        {
            this.DirectorateMembers = new HashSet<DirectorateMember>();
            this.GIAAAuditReports = new HashSet<GIAAAuditReport>();
            this.NAOPublications = new HashSet<NAOPublication>();
            this.Teams = new HashSet<Team>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public int DirectorateGroupID { get; set; }
        public Nullable<int> DirectorUserID { get; set; }
        public string Objectives { get; set; }
        public Nullable<int> EntityStatusID { get; set; }
        public Nullable<System.DateTime> EntityStatusDate { get; set; }
        public Nullable<System.DateTime> SysStartTime { get; set; }
        public Nullable<System.DateTime> SysEndTime { get; set; }
        public Nullable<int> ModifiedByUserID { get; set; }
        public Nullable<int> ReportApproverUserID { get; set; }
    
        public virtual DirectorateGroup DirectorateGroup { get; set; }
        public virtual EntityStatusType EntityStatusType { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DirectorateMember> DirectorateMembers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GIAAAuditReport> GIAAAuditReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NAOPublication> NAOPublications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Team> Teams { get; set; }
    }
}
