//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlAssuranceAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Element
    {
        public int ID { get; set; }
        public int FormId { get; set; }
        public Nullable<int> DefElementId { get; set; }
        public string Title { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CompletedOn { get; set; }
        public Nullable<int> AssignedTo { get; set; }
        public string GeneralNote { get; set; }
        public string ResponseA1 { get; set; }
        public string ResponseA2 { get; set; }
        public string ResponseA3 { get; set; }
        public string ResponseA4 { get; set; }
        public string ResponseA5 { get; set; }
        public string ResponseA6 { get; set; }
        public string ResponseA7 { get; set; }
        public string ResponseA8 { get; set; }
        public string ResponseA9 { get; set; }
        public string ResponseA10 { get; set; }
        public string ResponseAOther { get; set; }
        public string ResponseAOtherText { get; set; }
        public string ResponseAEffect { get; set; }
        public string ResponseAEffectText { get; set; }
        public string ResponseB1 { get; set; }
        public string ResponseB1Text { get; set; }
        public string ResponseB1Effect { get; set; }
        public string ResponseB2 { get; set; }
        public string ResponseB2Text { get; set; }
        public string ResponseB2Effect { get; set; }
        public string ResponseB3 { get; set; }
        public string ResponseB3Text { get; set; }
        public string ResponseB3Effect { get; set; }
        public string ResponseB4 { get; set; }
        public string ResponseB4Text { get; set; }
        public string ResponseB4Effect { get; set; }
        public Nullable<bool> NotApplicable { get; set; }
        public Nullable<bool> ResponseAEffectUnsatisfactory { get; set; }
        public Nullable<bool> ResponseAEffectLimited { get; set; }
        public Nullable<bool> ResponseAEffectModerate { get; set; }
        public Nullable<bool> ResponseAEffectSubstantial { get; set; }
        public Nullable<bool> ResponseAEffectNotApplicable { get; set; }
        public Nullable<bool> ResponseB1EffectUnsatisfactory { get; set; }
        public Nullable<bool> ResponseB1EffectLimited { get; set; }
        public Nullable<bool> ResponseB1EffectModerate { get; set; }
        public Nullable<bool> ResponseB1EffectSubstantial { get; set; }
        public Nullable<bool> ResponseB1EffectNotApplicable { get; set; }
        public Nullable<bool> ResponseB2EffectUnsatisfactory { get; set; }
        public Nullable<bool> ResponseB2EffectLimited { get; set; }
        public Nullable<bool> ResponseB2EffectModerate { get; set; }
        public Nullable<bool> ResponseB2EffectSubstantial { get; set; }
        public Nullable<bool> ResponseB2EffectNotApplicable { get; set; }
        public Nullable<bool> ResponseB3EffectUnsatisfactory { get; set; }
        public Nullable<bool> ResponseB3EffectLimited { get; set; }
        public Nullable<bool> ResponseB3EffectModerate { get; set; }
        public Nullable<bool> ResponseB3EffectSubstantial { get; set; }
        public Nullable<bool> ResponseB3EffectNotApplicable { get; set; }
    
        public virtual DefElement DefElement { get; set; }
        public virtual Form Form { get; set; }
    }
}
