//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlAssuranceAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailOutbox
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string ModuleName { get; set; }
        public string PersonName { get; set; }
        public string EmailTo { get; set; }
        public string emailCC { get; set; }
        public string Custom1 { get; set; }
        public string Custom2 { get; set; }
        public string Custom3 { get; set; }
        public string Custom4 { get; set; }
        public string Custom5 { get; set; }
        public string Custom6 { get; set; }
        public string Custom7 { get; set; }
        public string Custom8 { get; set; }
        public string Custom9 { get; set; }
        public string Custom10 { get; set; }
        public string Custom11 { get; set; }
        public string Custom12 { get; set; }
        public string Custom13 { get; set; }
        public string Custom14 { get; set; }
        public string Custom15 { get; set; }
        public string Custom16 { get; set; }
        public string Custom17 { get; set; }
        public string Custom18 { get; set; }
        public string Custom19 { get; set; }
        public string Custom20 { get; set; }
        public Nullable<int> MainEntityId { get; set; }
        public Nullable<int> EmailToUserId { get; set; }
        public string SubjectAndDescription { get; set; }
    }
}
