//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlAssuranceAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIAARecommendation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GIAARecommendation()
        {
            this.GIAAActionOwners = new HashSet<GIAAActionOwner>();
            this.GIAAUpdates = new HashSet<GIAAUpdate>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public string RecommendationDetails { get; set; }
        public Nullable<System.DateTime> TargetDate { get; set; }
        public Nullable<int> GIAAActionPriorityId { get; set; }
        public Nullable<int> GIAAActionStatusTypeId { get; set; }
        public Nullable<int> GIAAAuditReportId { get; set; }
        public Nullable<System.DateTime> RevisedDate { get; set; }
        public string OriginalImportedActionOwners { get; set; }
        public string DisplayedImportedActionOwners { get; set; }
        public string UpdateStatus { get; set; }
        public string Dept { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GIAAActionOwner> GIAAActionOwners { get; set; }
        public virtual GIAAActionPriority GIAAActionPriority { get; set; }
        public virtual GIAAActionStatusType GIAAActionStatusType { get; set; }
        public virtual GIAAAuditReport GIAAAuditReport { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GIAAUpdate> GIAAUpdates { get; set; }
    }
}
