//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlAssuranceAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIAAImport
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string XMLContents { get; set; }
        public string Status { get; set; }
        public string LogDetails { get; set; }
        public string LastImportStatus { get; set; }
        public Nullable<System.DateTime> LastImportDate { get; set; }
        public Nullable<int> LastImportById { get; set; }
    
        public virtual User User { get; set; }
    }
}
