//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlAssuranceAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIAAUpdate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GIAAUpdate()
        {
            this.GIAAUpdateFeedbacks = new HashSet<GIAAUpdateFeedback>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> TargetDate { get; set; }
        public string ProgressUpdateDetails { get; set; }
        public string GIAAComments { get; set; }
        public string Link { get; set; }
        public Nullable<int> GIAARecommendationId { get; set; }
        public Nullable<int> GIAAPeriodId { get; set; }
        public Nullable<int> GIAAActionStatusTypeId { get; set; }
        public Nullable<int> GIAAActionPriorityId { get; set; }
        public int GIAAUpdateStatusId { get; set; }
        public string UpdateChangeLog { get; set; }
    
        public virtual GIAAActionPriority GIAAActionPriority { get; set; }
        public virtual GIAAActionStatusType GIAAActionStatusType { get; set; }
        public virtual GIAAPeriod GIAAPeriod { get; set; }
        public virtual GIAARecommendation GIAARecommendation { get; set; }
        public virtual GIAAUpdateStatusType GIAAUpdateStatusType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GIAAUpdateFeedback> GIAAUpdateFeedbacks { get; set; }
    }
}
