//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlAssuranceAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoElement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GoElement()
        {
            this.GoAssignments = new HashSet<GoAssignment>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public Nullable<int> GoFormId { get; set; }
        public Nullable<int> GoDefElementId { get; set; }
        public string EvidenceStatement { get; set; }
        public string Rating { get; set; }
        public string CompletionStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoAssignment> GoAssignments { get; set; }
        public virtual GoDefElement GoDefElement { get; set; }
        public virtual GoForm GoForm { get; set; }
    }
}
