//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlAssuranceAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoForm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GoForm()
        {
            this.GoElements = new HashSet<GoElement>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public Nullable<int> PeriodId { get; set; }
        public Nullable<int> DirectorateGroupId { get; set; }
        public string SummaryRagRating { get; set; }
        public string SummaryEvidenceStatement { get; set; }
        public string SummaryCompletionStatus { get; set; }
        public Nullable<bool> SummaryMarkReadyForApproval { get; set; }
        public string SpecificAreasCompletionStatus { get; set; }
        public string DGSignOffStatus { get; set; }
        public Nullable<int> DGSignOffUserId { get; set; }
        public Nullable<System.DateTime> DGSignOffDate { get; set; }
    
        public virtual DirectorateGroup DirectorateGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoElement> GoElements { get; set; }
        public virtual Period Period { get; set; }
        public virtual User User { get; set; }
    }
}
