//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlAssuranceAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IAPAction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IAPAction()
        {
            this.IAPActionDirectorates = new HashSet<IAPActionDirectorate>();
            this.IAPActionUpdates = new HashSet<IAPActionUpdate>();
            this.IAPAssignments = new HashSet<IAPAssignment>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public string Details { get; set; }
        public Nullable<int> IAPPriorityId { get; set; }
        public Nullable<int> IAPStatusTypeId { get; set; }
        public Nullable<int> IAPTypeId { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string Attachment { get; set; }
        public Nullable<bool> IsLink { get; set; }
        public Nullable<System.DateTime> OriginalCompletionDate { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public Nullable<bool> MonthlyUpdateRequired { get; set; }
        public Nullable<bool> MonthlyUpdateRequiredIfNotCompleted { get; set; }
        public Nullable<bool> IsArchive { get; set; }
    
        public virtual IAPPriority IAPPriority { get; set; }
        public virtual IAPStatusType IAPStatusType { get; set; }
        public virtual IAPType IAPType { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IAPActionDirectorate> IAPActionDirectorates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IAPActionUpdate> IAPActionUpdates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IAPAssignment> IAPAssignments { get; set; }
    }
}
