//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlAssuranceAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NAOOutput
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public Nullable<int> NAOPeriodId { get; set; }
        public Nullable<int> DirectorateGroupId { get; set; }
        public string PdfStatus { get; set; }
        public Nullable<System.DateTime> PdfDate { get; set; }
        public string PdfName { get; set; }
        public string PeriodUpdateStatus { get; set; }
    
        public virtual DirectorateGroup DirectorateGroup { get; set; }
        public virtual NAOPeriod NAOPeriod { get; set; }
    }
}
