//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlAssuranceAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NAORecommendation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NAORecommendation()
        {
            this.NAOAssignments = new HashSet<NAOAssignment>();
            this.NAOUpdates = new HashSet<NAOUpdate>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public string RecommendationDetails { get; set; }
        public Nullable<int> NAOPublicationId { get; set; }
        public Nullable<int> NAOUpdateStatusTypeId { get; set; }
        public string Conclusion { get; set; }
        public string OriginalTargetDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NAOAssignment> NAOAssignments { get; set; }
        public virtual NAOPublication NAOPublication { get; set; }
        public virtual NAOUpdateStatusType NAOUpdateStatusType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NAOUpdate> NAOUpdates { get; set; }
    }
}
