//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlAssuranceAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NAOUpdate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NAOUpdate()
        {
            this.NAOUpdateEvidences = new HashSet<NAOUpdateEvidence>();
            this.NAOUpdateFeedbacks = new HashSet<NAOUpdateFeedback>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public string TargetDate { get; set; }
        public string ActionsTaken { get; set; }
        public string NAOComments { get; set; }
        public string FurtherLinks { get; set; }
        public Nullable<int> NAORecommendationId { get; set; }
        public Nullable<int> NAOPeriodId { get; set; }
        public Nullable<int> NAORecStatusTypeId { get; set; }
        public int NAOUpdateStatusTypeId { get; set; }
        public string UpdateChangeLog { get; set; }
    
        public virtual NAOPeriod NAOPeriod { get; set; }
        public virtual NAORecommendation NAORecommendation { get; set; }
        public virtual NAORecStatusType NAORecStatusType { get; set; }
        public virtual NAOUpdateStatusType NAOUpdateStatusType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NAOUpdateEvidence> NAOUpdateEvidences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NAOUpdateFeedback> NAOUpdateFeedbacks { get; set; }
    }
}
